name: 'Push to SFTP'
description: 'Push files to your server via SFTP (no SSH needed!)'
inputs:
  host:
    description: 'SFTP server'
    required: true
    default: ''
  port:
    description: 'SFTP server port'
    required: true
    default: '22'
  username:
    description: 'SFTP username'
    required: false
    default: ''
  password:
    description: 'SFTP password'
    required: false
    default: ''
  privateKey:
    description: "SSH Key"
    required: false
  passphrase:
    description: "Passphrase for encrypted private keys"
    required: false
  sourceDir:
    description: 'Source directory to upload from (will upload all files in this directory)'
    required: true
    default: ''
  targetDir:
    description: 'Remote directory to upload to (WARNING: overwrites ALL files in this directory)'
    required: true
    default: ''
  
runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'upload-cloud'  
  color: 'yellow'