name: 'Push to SFTP'
description: 'Push files to your server via SFTP (no SSH needed!)'
inputs:
  host:
    description: 'SFTP server'
    required: true
    default: ''
  port:
    description: 'SFTP server port'
    required: true
    default: '22'
  username:
    description: 'SFTP username'
    required: true
    default: ''
  password:
    description: 'SFTP password'
    required: true
    default: ''
  sourceDir:
    description: 'Source directory to upload from (will upload all files in this directory)'
    required: true
    default: ''
  targetDir:
    description: 'Remote directory to upload to (WARNING: overwrites ALL files in this directory)'
    required: true
    default: ''
  onlyModifiedFiles:
    description: 'Boolean value. If set to `true` will only upload modified files'
    required: false
    default: false
  token:
    description: 'Token with access to your repository scoped in as a secret. You will only need this if `onlyModifiedFiles` is set to `true`. See https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret for more info'
    required: false
    default: ''
  
runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'upload-cloud'  
  color: 'yellow'